Survey Monkey request without json body
ghassani/surveymonkey-v3-api-php pull request #29
Opened 2020-06-06 15:01 UTC by ken-mills

Survey Monkey moved to CloudFront on 2020-05-23.   CloudFront issues 403 Forbidden with empty json body. Removed body from request.

I'm kinda new at this so please provide feedback if I screwed up.

2020-06-06 15:05 UTC, ken-mills commented
Closes #28

2020-06-08 20:52 UTC, ghassani requested changes
You are never assigning the $bodyContent to the request when there is content to send. You need to create the request after whatever the bodyContent ends up being.

2020-06-08 23:38 UTC, ken-mills commented
Oops sorry. Change submitted. I am working on a test with a body in the post.

2020-06-09 20:39 UTC, ghassani commented
It is still incorrect. I went ahead and commit the change to master, thanks for the effort though. Go ahead and try the master branch and see if it fixes your issues and if it does I will make a release.

2020-06-09 20:39 UTC, closed without merging